// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2dBurgerWebAPI.Data;

#nullable disable

namespace _2dBurgerWebAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231222060051_ForeignKey-Producto-ComidasCombo")]
    partial class ForeignKeyProductoComidasCombo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_2dBurgerWebAPI.Models.AtributoProducto<decimal>", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("codigo");

                    b.ToTable("AtributoProducto<decimal>");
                });

            modelBuilder.Entity("_2dBurgerWebAPI.Models.AtributoProducto<string>", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.ToTable("AtributoProducto<string>");
                });

            modelBuilder.Entity("_2dBurgerWebAPI.Models.ComidasCombo", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("codigoCombo")
                        .HasColumnType("int");

                    b.Property<int>("codigoComida")
                        .HasColumnType("int");

                    b.HasKey("codigo");

                    b.HasIndex("codigoCombo");

                    b.HasIndex("codigoComida");

                    b.ToTable("ComidasCombo");
                });

            modelBuilder.Entity("_2dBurgerWebAPI.Models.Producto", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"));

                    b.Property<int>("codigoDescripcionActual")
                        .HasColumnType("int");

                    b.Property<int>("codigoDescuentoActual")
                        .HasColumnType("int");

                    b.Property<int>("codigoNombreActual")
                        .HasColumnType("int");

                    b.Property<int>("codigoPrecioActual")
                        .HasColumnType("int");

                    b.HasKey("codigo");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("_2dBurgerWebAPI.Models.ComidasCombo", b =>
                {
                    b.HasOne("_2dBurgerWebAPI.Models.Producto", "combo")
                        .WithMany("comidas")
                        .HasForeignKey("codigoCombo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_2dBurgerWebAPI.Models.Producto", "comida")
                        .WithMany("combos")
                        .HasForeignKey("codigoComida")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("combo");

                    b.Navigation("comida");
                });

            modelBuilder.Entity("_2dBurgerWebAPI.Models.Producto", b =>
                {
                    b.Navigation("combos");

                    b.Navigation("comidas");
                });
#pragma warning restore 612, 618
        }
    }
}
